# Generated by Django 5.0.3 on 2025-01-11 15:32

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dish', '0002_initial'),
        ('user', '0002_deliveryaddress_user_role_userdeliveryaddress'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='payment',
        ),
        migrations.AddField(
            model_name='dish',
            name='cuisine',
            field=models.CharField(choices=[('russian_cuisine', 'Русская кухня'), ('georgian_cuisine', 'Грузинская кухня'), ('italian_cuisine', 'Итальянская кухня'), ('japanese_cuisine', 'Японская кухня')], default=1, max_length=100, verbose_name='Вид кухни'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='order',
            name='address',
            field=models.ForeignKey(blank=True, max_length=254, null=True, on_delete=django.db.models.deletion.SET_NULL, to='user.deliveryaddress', verbose_name='Адрес доставки'),
        ),
        migrations.AddField(
            model_name='order',
            name='comment',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='Комментарий'),
        ),
        migrations.AddField(
            model_name='order',
            name='count_dishes',
            field=models.PositiveSmallIntegerField(default=0, verbose_name='Количество блюд'),
        ),
        migrations.AddField(
            model_name='order',
            name='courier',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='courier_orders', to=settings.AUTH_USER_MODEL, verbose_name='Курьер'),
        ),
        migrations.AddField(
            model_name='order',
            name='delivery_time',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Дата и время доставки'),
        ),
        migrations.AddField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('awaiting_payment', 'ожидание оплаты'), ('awaiting_courier', 'ожидание курьера'), ('deliver', 'доставляем'), ('delivered', 'доставлен'), ('cancelled', 'отменен')], default='awaiting_payment', max_length=100, verbose_name='Статус'),
        ),
        migrations.AlterField(
            model_name='order',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orders', to=settings.AUTH_USER_MODEL, verbose_name='Клиент'),
        ),
    ]
